runtime: python39

handlers:
  # Serve the root `index.html` for the base URL
  - url: /
    static_files: index.html
    upload: index.html
    
  - url: /static
    static_dir: static
    
  - url: /.*
    script: auto
